export const FECTH_REQUESTS = 'FECTH_REQUESTS';
export const GOOGLE_SIGN_IN_START = 'GOOGLE_SIGN_IN_START';
export const GOOGLE_SIGN_IN_SUCCESS = 'GOOGLE_SIGN_IN_SUCCESS';
export const GOOGLE_SIGN_IN_FAIL = 'GOOGLE_SIGN_IN_FAIL';

export const FACEBOOK_SIGN_IN_START = 'FACEBOOK_SIGN_IN_START';
export const FACEBOOK_SIGN_IN_SUCCESS = 'FACEBOOK_SIGN_IN_SUCCESS';
export const FACEBOOK_SIGN_IN_FAIL = 'FACEBOOK_SIGN_IN_FAIL';

export const FETCH_ACCOMMODATIONS_LOADING = 'FETCH_ACCOMMODATIONS_LOADING';
export const FETCH_ACCOMMODATIONS_SUCCESS = 'FETCH_ACCOMMODATIONS_SUCCESS';
export const FETCH_ACCOMMODATIONS_FAILED = 'FETCH_ACCOMMODATIONS_FAILED';

export const FETCH_SINGLE_ACCOMMODATION_LOADING = 'FETCH_SINGLE_ACCOMMODATION_LOADING';
export const FETCH_SINGLE_ACCOMMODATION_SUCCESS='FETCH_SINGLE_ACCOMMODATION_SUCCESS';
export const FETCH_SINGLE_ACCOMMODATION_FAILED='FETCH_SINGLE_ACCOMMODATION_FAILED';


export const FETCH_USER_LOADING = 'FETCH_USER_LOADING';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';


export const FETCH_ROLE_LOADING = 'FETCH_ROLE_LOADING';
export const FETCH_ROLE_SUCCESS = 'FECTH_ROLE_SUCCESS';
export const FETCH_ROLE_FAILED = 'FECTH_ROLE_FAILED';


export const ASSIGN_ROLE_LOADING = 'ASSIGN_ROLE_LOADING';
export const ASSIGN_ROLE_SUCCESS = 'ASSIGN_ROLE_SUCCESS';
export const ASSIGN_ROLE_FAILED = 'ASSIGN_ROLE_FAILED';

export const ACCOMMODATION_UPDATE_LOADING = 'ACCOMMODATION_UPDATE_LOADING';
export const ACCOMMODATION_UPDATE_SUCCESS = 'ACCOMMODATION_UPDATE_SUCCESS';
export const ACCOMMODATION_UPDATE_FAILURE = 'ACCOMMODATION_UPDATE_FAILURE';

export const ACCOMMODATION_DELETE_LOADING = 'ACCOMMODATION_DELETE_LOADING';
export const ACCOMMODATION_DELETE_SUCCESS = 'ACCOMMODATION_DELETE_SUCCESS';
export const ACCOMMODATION_DELETE_FAILURE = 'ACCOMMODATION_DELETE_FAILURE';

export const ACCOMMODATION_VIEW_LOADING = 'ACCOMMODATION_VIEW_LOADING';
export const ACCOMMODATION_VIEW_SUCCESS = 'ACCOMMODATION_VIEW_SUCCESS';
export const ACCOMMODATION_VIEW_FAILURE = 'ACCOMMODATION_VIEW_FAILURE';