export const SET_USER_ONLINE_STATUS = 'SET_USER_ONLINE_STATUS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const READ_NOTIFICATION = 'READ_NOTIFICATION';
export const READ_ALL_NOTIFICATIONS = 'READ_ALL_NOTIFICATION';
export const RESET_UNREAD_NOTIFICATIONS = 'RESET_UNREAD_NOTIFICATIONS';
