
export const FETCH_USER_PROFILE_LOADING = "FETCH_USER_PROFILE_LOADING";
export const FETCH_USER_PROFILE_SUCCESS = "FETCH_USER_PROFILE_SUCCESS";
export const FETCH_USER_PROFILE_FAILED = "FETCH_USER_PROFILE_FAILED";

export const UPDATE_USER_PROFILE_LOADING = "UUPDATE_USER_PROFILE_LOADING";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILED = "UPDATE_USER_PROFILE_FAILED";
